# Config file for codeml pipeline
CODEML_GET_INPUT: true
CODEML_RUN: true
CODEML_ANALYSIS: true
OUTPUT_DIR: ./output_test

GROUP: Astroviridae_43
GROUPING_COLUMN: Host
ACCESSIONS_FILE: ./input/test.txt
REF_ACC: OQ198042.1
REF_CDS_ID: ""
ROOTED_TREE_PATH: ./input/rooted_trees/${GROUP}.rooted.anc_recon.tree
TARGET_LABEL: Canis
MAX_TREE_LEAVES: 150
ALIGN_CODONS_WITH: mafft
PV_TABLE_FILE: input/PVT.3SEQ.400
PV_DIM: 400
STEP: 200
ANALYSIS: site-model

## overwrite default
CODEML_RESULTS_DIR: "${OUTPUT_DIR}/codeml/output/${GROUP}_test_$(date +%Y%m%d_%H%M%S)"


